export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';

//Auth
export const GET_AUTHINFO = 'GET_AUTHINFO';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const UPDATE_USERDATA = 'UPDATE_USERDATA';
export const AUTH_ERRORRESET = 'AUTH_ERRORRESET';
