export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';

//Search
export const GET_SEARCHRESULTS = 'GET_SEARCHRESULTS';
export const SEARCH_RESET = 'SEARCH_RESET';
export const PAGE_CHANGE = 'PAGE_CHANGE';

//Auth
export const GET_AUTHINFO = 'GET_AUTHINFO';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const UPDATE_USERDATA = 'UPDATE_USERDATA';

//Like
export const GET_USERLIKES = 'GET_USERLIKES';
export const GET_CURRENTLIKE = 'GET_CURRENTLIKE';
export const CREATE_USERLIKE = 'CREATE_USERLIKE';
export const DELETE_USERLIKE = 'DELETE_USERLIKE';
export const SET_LIKESTATUS = 'SET_LIKESTATUS';

//Comment
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

//Subscriptions
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const GET_CURRENTSUB = 'GET_CURRENTSUB';
export const ADD_SUBSCRIBE = 'ADD_SUBSCRIBE';
export const DELETE_SUBSCRIBE = 'DELETE_SUBSCRIBE';
export const SET_SUBSCRIBESTATUS = 'SET_SUBSCRIBESTATUS';

//Alerts
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
